import type { AppLocale } from "./locale";

/** نصوص الواجهة — عند اختيار EN يُستعمل الفرع الإنجليزي بالكامل حيث طُبّق. */
const AR = {
  landing: {
    nameAr: "عَمارتي",
    tagline: "إدارة المباني الذكية",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logoAlt: "عَمارتي",
  },
  login: {
    title: "تسجيل الدخول",
    subtitle: "",
    identifier: "الجوال أو البريد",
    password: "كلمة المرور",
    showPassword: "إظهار كلمة المرور",
    hidePassword: "إخفاء كلمة المرور",
    submit: "دخول",
    submitPending: "جاري تسجيل الدخول…",
    noAccount: "ليس لديك حساب؟",
    signUp: "أنشئ حساباً جديداً",
    noAccountFull: "لا يوجد حساب بهذا الجوال أو البريد.",
    invalidForm: "بيانات غير صالحة",
    invalidCredentials: "رقم الجوال أو البريد أو كلمة المرور غير صحيحة",
  },
  signup: {
    chooseTitle: "أنشئ حسابك",
    chooseSubtitle: "انضم إلى عمارتك برمز المبنى ورقم شقتك.",
    choiceCreateTitle: "إنشاء مبنى جديد",
    choiceCreateDesc: "تسجيل عمارة جديدة ومشاركة رمز الدعوة مع السكان.",
    choiceJoinTitle: "الانضمام إلى مبنى",
    choiceJoinDesc: "انضم إلى عمارتك برمز المبنى ورقم شقتك.",
    haveAccount: "لديك حساب؟",
    backLogin: "تسجيل الدخول",
    yourInfoTitle: "بياناتك",
    buildingInfoTitle: "بيانات المبنى",
    joinInfoTitle: "بيانات الانضمام",
    submitCreate: "إنشاء الحساب وتسجيل المبنى",
    submitJoin: "إنشاء الحساب والانضمام",
    submitPending: "جاري المعالجة…",
    headerCreate: "إنشاء حساب — مبنى جديد",
    headerJoin: "إنشاء حساب — انضمام إلى مبنى",
    inviteCodeNotFound: "رمز المبنى غير صحيح أو غير موجود.",
    addressInvalid:
      "تحقق من اسم العمارة ورقم الشقة وحقول العنوان الوطني (المنطقة، المدينة، الحي، الشارع، رقم المبنى، الرمز البريدي).",
    invalidEmail:
      "صيغة البريد غير صالحة. أدخل بريداً صحيحاً أو اترك الحقل فارغاً.",
  },
  register: {
    name: "الاسم",
    email: "البريد (اختياري)",
    phone: "الجوال (إلزامي)",
    password: "كلمة المرور",
    invalidForm: "بيانات غير صالحة",
    emailTaken: "البريد مسجل مسبقاً",
    phoneTaken: "رقم الجوال مسجل مسبقاً",
  },
  dashboard: {
    title: "ابدأ مع عَمارتي",
    subtitle: "انضم إلى مبنى قائم برمز المبنى ورقم شقتك.",
    createBuildingDisabled: "إنشاء مبنى جديد غير متاح من التطبيق. استخدم رمز المبنى للانضمام.",
    nationalAddressTitle: "العنوان الوطني",
    nationalAddressHelp:
      "أدخل بيانات العنوان الوطني وفق معايير البريد السعودي (العنوان الوطني).",
    addressLine: "العنوان",
    addressLinePh: "مثال: حي النخيل، شارع الملك فهد",
    addressHelp:
      "اكتب وصفًا نصّيًا لموقع المبنى (الشارع أو الحي) مع المدينة — كما تناسبك.",
    name: "اسم العمارة",
    namePh: "مثال: عمارة النور",
    region: "المنطقة",
    regionPh: "مثال: منطقة الرياض",
    city: "المدينة",
    cityPh: "مثال: الرياض",
    district: "الحي",
    streetName: "اسم الشارع",
    buildingNumber: "رقم المبنى",
    additionalNumber: "الرقم الإضافي (اختياري)",
    postalCode: "الرمز البريدي (5 أرقام)",
    shortAddressCode: "الرمز المختصر (8 خانات، اختياري)",
    unitLabel: "رقم شقتك",
    unitPh: "مثال: 303",
    joinCard: "الانضمام برمز المبنى",
    joinHint: "أدخل رمز المبنى ورقم شقتك.",
    alreadyInBuilding: "حسابك مرتبط بمبنى آخر. كل مستخدم ينتمي لمبنى واحد فقط.",
    inviteCode: "رمز المبنى",
    unitNumber: "رقم الشقة",
    joinSubmit: "انضمام",
    owner: "مالك",
    tenant: "مستأجر",
  },
  buildingNav: {
    maintenance: "صيانة",
    votes: "تصويت",
    announcements: "إعلانات",
    supervisor: "لوحة المشرف",
  },
  buildingHome: {
    youSupervisor: "أنت المشرف",
    unitPrefix: "شقة",
    shortcuts: "اختصارات سريعة",
    linkInvite: "رمز المبنى",
    linkPassport: "جواز الشقة",
    overviewSection: "نظرة عامة",
    openChat: "محادثة جماعية",
    openAssistant: "مساعد ذكي",
  },
  maintenance: {
    newRequest: "طلب صيانة جديد",
    aiHint:
      "يحلّل وصف المشكلة (شخصية أو مجتمعية)، يقدّر نافذة زمنية للصيانة والحد الأقصى للانتظار، ثم يقترح شركات صيانة. للصيانة المجتمعية يُفتح تصويت تلقائياً على الشركات المقترحة.",
    type: "النوع",
    scopePersonal: "صيانة شخصية (شقتك)",
    scopeCommunity: "صيانة مجتمعية (مشتركة)",
    title: "عنوان مختصر",
    problem: "وصف المشكلة",
    submitAi: "إرسال مع تحليل وتوصيات الذكاء الاصطناعي",
    requests: "الطلبات",
    noneRequests: "لا طلبات صيانة بعد.",
    personalUnit: "شخصي — شقة",
    community: "مجتمعي",
    analysis: "تحليل",
    suggestions: "توصيات",
    aiTag: "تحليل ذكاء اصطناعي",
    aiCompanies: "شركات صيانة مقترحة:",
    startCompanyVote: "بدء تصويت لاختيار شركة صيانة",
    companyVoteOpen: "يوجد تصويت جاري لشركة الصيانة — تابع من قسم «تصويت».",
    scopeLabelPersonal: "شخصي",
    scopeLabelCommunity: "مجتمعي",
  },
  assistant: {
    title: "المساعد الذكي",
    welcomeMessage:
      "👋 أهلًا بك في عمارتي!\n\nأنا مساعدك الذكي، جاهز أسهّل عليك إدارة شقتك وعمارتك بخطوات بسيطة وواضحة.\n\nمن متابعة الصيانة، واستقبال البلاغات، وتنظيم السكن... إلى متابعة المدفوعات والتنبيهات — كل شيء عندك في مكان واحد 👇\n\nإذا احتجت أي مساعدة، اسألني مباشرة... وأنا هنا دائماً لخدمتك ✨\n\nخلينا نبدأ معاً بتجربة إدارة أسهل، أسرع، وأذكى مع عمارتي 🏢💙",
    quickStatus: "معلومات شقتي",
    quickMaintenance: "عرض طلبات الصيانة",
    placeholder: "اكتب رسالتك...",
    demoReply:
      "سأساعدك في استخدام التطبيق خطوة بخطوة. جرّب من الشريط السفلي: الرئيسية، الصيانة، التصويت، والحساب. اسألني عن الانضمام برمز المبنى أو تقديم طلب صيانة.",
  },
  chat: {
    conversationsTitle: "المحادثات",
    tabResidents: "السكان",
    tabGroup: "محادثة جماعية",
    emptyGroup: "لا رسائل بعد — اكتب أول رسالة للسكان أدناه.",
    emptyResidents: "لا يوجد سكان مسجّلون في المبنى بعد.",
    placeholder: "اكتب رسالتك...",
  },
  votes: {
    titleSupervisor: "تصويت اختيار المشرف",
    titleCompany: "تصويت شركات الصيانة (الأعطال المجتمعية)",
    titleOther: "تصويتات أخرى",
    kindsTitle: "خيارات التصويت",
    kindSupervisorTitle: "تصويت لاختيار مشرف",
    kindSupervisorDesc: "يحق لمنشئ المبنى فقط بدء تصويت اختيار المشرف.",
    kindCompanyTitle: "تصويت شركة صيانة (مجتمعي)",
    kindCompanyDesc:
      "عند تقديم طلب صيانة مجتمعي يُنشأ تصويت تلقائياً على الشركات المقترحة.",
    creatorOnlyHint: "يحق لمنشئ المبنى فقط بدء تصويت المشرف.",
    openMaintenance: "فتح قسم الصيانة لاختيار طلب",
    typeSupervisor: "مشرف",
    typeCompany: "شركة صيانة",
    typeLegacyPoll: "تصويت (أرشيف)",
    statusActive: "جاري",
    statusEnded: "منتهٍ",
    ends: "ينتهي",
    votes: "صوت",
    vote: "صوّت",
    yourVote: "صوتك هنا",
    startSupervisor: "بدء تصويت المشرف",
    closeSupervisor: "إغلاق وتعيين المشرف الفائز",
    closeCompany: "إغلاق التصويت وتسجيل الشركة الفائزة",
    none: "لا تصويتات بعد.",
  },
  supervisor: {
    only: "هذه الصفحة للمشرف فقط.",
    panelTitle: "لوحة المشرف",
    refreshTitle: "تحديث السكور والتنبؤات",
    refreshP1:
      "زر «تحديث الآن» يُحدّث سكور صحة المبنى الشهري من سجل طلبات الصيانة.",
    refreshBtn: "تحديث الآن",
    scoreTitle: "سجل السكور الشهري",
    scoreEmpty: "اضغط «تحديث الآن» لإنشاء أول سجل.",
    scoreScaleRange: "النطاق",
    scoreScaleLabel: "التصنيف",
    scoreScaleDesc: "الوصف",
  },
  announcements: {
    new: "إعلان جديد",
    titlePh: "عنوان الإعلان",
    bodyPh: "تفاصيل...",
    publish: "نشر",
    recent: "آخر الإعلانات",
    delete: "حذف",
  },
  passport: {
    title: "جواز الشقة",
  },
  invitePage: {
    publicCode: "رمز المبنى العام",
    shareHintBefore: "شارك الرمز مع الجيران لينضموا برقم شقتهم:",
  },
  join: {
    invalidTitle: "رابط غير صالح",
    expired: "قد يكون منتهي الصلاحية.",
    backDashboard: "العودة للوحة التحكم",
    inviteTitle: "دعوة للانضمام",
    building: "المبنى",
    unit: "الشقة",
    kind: "النوع",
    accept: "قبول والانضمام",
  },
  profile: {
    title: "الحساب",
    subtitle: "",
    accountTitle: "بيانات الحساب",
    name: "الاسم",
    email: "البريد (اختياري)",
    phone: "الجوال (إلزامي)",
    save: "حفظ التغييرات",
    saving: "جاري الحفظ…",
    saved: "تم حفظ بياناتك.",
    invalidForm: "بيانات غير صالحة. يجب أن يكون الاسم حرفين فأكثر.",
    invalidEmail:
      "صيغة البريد غير صالحة. أدخل بريداً صحيحاً أو امسح الحقل.",
    emailOptionalPlaceholder: "يمكن إضافة بريد لاحقًا",
    settingsTitle: "الإعدادات",
    themeLabel: "المظهر",
    themeToggle: "تبديل المظهر (فاتح / داكن)",
    residentsVisibilityLabel: "الظهور في قائمة السكان",
    residentsVisibleOn: "يظهر اسمك في قائمة سكان المبنى",
    residentsVisibleOff: "اسمك مخفي عن قائمة السكان",
    notificationsLabel: "إشعارات المتصفح",
    notificationsOn: "مفعّلة",
    notificationsOff: "متوقفة",
    notificationsHint: "",
    logout: "تسجيل الخروج",
    memberSince: "عضو منذ",
    passportTitle: "جواز الشقة",
    passportHint: "",
    passportNoUnits: "لم تنضم إلى أي مبنى بعد.",
    passportNoEvents: "لا سجلات لهذه الوحدة بعد.",
    passportOpen: "فتح جواز الوحدة",
  },
} as const;

type Messages = typeof AR;

const EN = {
  landing: {
    nameAr: "عماراتي",
    tagline: "Smart building management",
    login: "Log in",
    register: "Sign up",
    logoAlt: "Amarati",
  },
  login: {
    title: "Log in",
    subtitle: "",
    identifier: "Phone or email",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    submit: "Sign in",
    submitPending: "Signing in…",
    noAccount: "Don’t have an account?",
    signUp: "Create a new account",
    noAccountFull: "No account with this phone number or email.",
    invalidForm: "Invalid data",
    invalidCredentials: "Incorrect phone/email or password.",
  },
  signup: {
    chooseTitle: "Create your account",
    chooseSubtitle: "Join your building with the building code and unit number.",
    choiceCreateTitle: "Register a new building",
    choiceCreateDesc: "Register a new building and share the invite code with residents.",
    choiceJoinTitle: "Join a building",
    choiceJoinDesc: "Join your building with the building code and unit number.",
    haveAccount: "Already have an account?",
    backLogin: "Log in",
    yourInfoTitle: "Your details",
    buildingInfoTitle: "Building details",
    joinInfoTitle: "Join details",
    submitCreate: "Create account & register building",
    submitJoin: "Create account & join",
    submitPending: "Working…",
    headerCreate: "Create account — new building",
    headerJoin: "Create account — join building",
    inviteCodeNotFound: "Building code is invalid or not found.",
    addressInvalid:
      "Check the building name, unit number, and national address fields (region, city, district, street, building number, postal code).",
    invalidEmail:
      "That email doesn’t look valid. Enter a correct address or leave the field blank.",
  },
  register: {
    name: "Name",
    email: "Email (optional)",
    phone: "Phone (required)",
    password: "Password",
    invalidForm: "Invalid data",
    emailTaken: "This email is already registered",
    phoneTaken: "This phone number is already registered",
  },
  dashboard: {
    title: "Get started with Amarati",
    subtitle: "Join an existing building with a code and your unit number.",
    createBuildingDisabled:
      "Creating a new building is not available in the app. Use a building code to join.",
    nationalAddressTitle: "National address",
    nationalAddressHelp:
      "Enter your national address per Saudi Post standards (National Address).",
    addressLine: "Street / area",
    addressLinePh: "e.g. Al-Nakheel district, King Fahd Road",
    addressHelp: "Describe the street or neighbourhood plus city — plain text.",
    name: "Building name",
    namePh: "e.g. Al-Noor Tower",
    region: "Region",
    regionPh: "e.g. Riyadh Region",
    city: "City",
    cityPh: "e.g. Riyadh",
    district: "District",
    streetName: "Street name",
    buildingNumber: "Building number",
    additionalNumber: "Additional number (optional)",
    postalCode: "Postal code (5 digits)",
    shortAddressCode: "Short address code (8 chars, optional)",
    unitLabel: "Your unit number",
    unitPh: "e.g. 303",
    joinCard: "Join with building code",
    joinHint: "Enter the building code and your unit number.",
    alreadyInBuilding:
      "Your account is already linked to another building. Each user belongs to one building only.",
    inviteCode: "Building code",
    unitNumber: "Unit number",
    joinSubmit: "Join",
    owner: "Owner",
    tenant: "Tenant",
  },
  buildingNav: {
    maintenance: "Maintenance",
    votes: "Votes",
    announcements: "Announcements",
    supervisor: "Supervisor",
  },
  buildingHome: {
    youSupervisor: "You are the supervisor",
    unitPrefix: "Unit",
    shortcuts: "Quick shortcuts",
    linkInvite: "Building code",
    linkPassport: "Unit passport",
    overviewSection: "Overview",
    openChat: "Group chat",
    openAssistant: "Smart assistant",
  },
  maintenance: {
    newRequest: "New maintenance request",
    aiHint:
      "The model reads your description (personal or community), estimates a maintenance window and a maximum wait, then suggests companies. Community requests automatically open a vote on those companies.",
    type: "Type",
    scopePersonal: "Personal (your unit)",
    scopeCommunity: "Community (shared)",
    title: "Short title",
    problem: "Problem description",
    submitAi: "Submit with AI analysis & recommendations",
    requests: "Requests",
    noneRequests: "No maintenance requests yet.",
    personalUnit: "Personal — unit",
    community: "Community",
    analysis: "Analysis",
    suggestions: "Suggestions",
    aiTag: "AI analysis",
    aiCompanies: "Suggested maintenance companies:",
    startCompanyVote: "Start vote to pick a maintenance company",
    companyVoteOpen: "A maintenance company vote is in progress — see the Voting tab.",
    scopeLabelPersonal: "Personal",
    scopeLabelCommunity: "Community",
  },
  assistant: {
    title: "Smart assistant",
    welcomeMessage:
      "👋 Welcome to Amarati!\n\nI'm your smart assistant, here to make managing your unit and building simple and clear.\n\nFrom maintenance and reports to housing organization, payments, and alerts — everything in one place 👇\n\nAsk me anytime — I'm always here to help ✨\n\nLet's start an easier, faster, smarter building experience with Amarati 🏢💙",
    quickStatus: "My unit overview",
    quickMaintenance: "View maintenance requests",
    placeholder: "Write your message…",
    demoReply:
      "I'll guide you through the app step by step. Use the bottom bar: Home, Maintenance, Votes, and Account. Ask about joining with a building code or filing maintenance.",
  },
  chat: {
    conversationsTitle: "Conversations",
    tabResidents: "Residents",
    tabGroup: "Group chat",
    emptyGroup: "No messages yet — send the first one below.",
    emptyResidents: "No residents registered in this building yet.",
    placeholder: "Write your message…",
  },
  votes: {
    titleSupervisor: "Supervisor election votes",
    titleCompany: "Maintenance-company votes (community issues)",
    titleOther: "Other votes",
    kindsTitle: "Vote types",
    kindSupervisorTitle: "Supervisor election",
    kindSupervisorDesc: "Only the building creator can start supervisor voting.",
    kindCompanyTitle: "Maintenance-company vote (community)",
    kindCompanyDesc:
      "When someone files a community maintenance request, a vote is created automatically on suggested companies.",
    creatorOnlyHint: "Only the building creator can start a supervisor vote.",
    openMaintenance: "Open maintenance to pick a request",
    typeSupervisor: "Supervisor",
    typeCompany: "Maintenance company",
    typeLegacyPoll: "Poll (archive)",
    statusActive: "Active",
    statusEnded: "Ended",
    ends: "Ends",
    votes: "votes",
    vote: "Vote",
    yourVote: "Your vote",
    startSupervisor: "Start supervisor vote",
    closeSupervisor: "Close and assign winning supervisor",
    closeCompany: "Close vote and record the winning company",
    none: "No votes yet.",
  },
  supervisor: {
    only: "Supervisors only.",
    panelTitle: "Supervisor panel",
    refreshTitle: "Refresh score & predictions",
    refreshP1:
      "“Update now” refreshes the monthly building health score from the maintenance request log.",
    refreshBtn: "Update now",
    scoreTitle: "Monthly score log",
    scoreEmpty: "Click “Update now” to create the first record.",
    scoreScaleRange: "Range",
    scoreScaleLabel: "Rating",
    scoreScaleDesc: "Description",
  },
  announcements: {
    new: "New announcement",
    titlePh: "Title",
    bodyPh: "Details…",
    publish: "Publish",
    recent: "Recent announcements",
    delete: "Delete",
  },
  passport: {
    title: "Digital passport — unit",
  },
  invitePage: {
    publicCode: "Public building code",
    shareHintBefore: "Share this code so neighbours can join with their unit number:",
  },
  join: {
    invalidTitle: "Invalid link",
    expired: "It may have expired.",
    backDashboard: "Back to dashboard",
    inviteTitle: "Invitation to join",
    building: "Building",
    unit: "Unit",
    kind: "Role",
    accept: "Accept and join",
  },
  profile: {
    title: "Account",
    subtitle: "",
    accountTitle: "Account details",
    name: "Name",
    email: "Email (optional)",
    phone: "Phone (required)",
    save: "Save changes",
    saving: "Saving…",
    saved: "Your profile has been updated.",
    invalidForm: "Invalid data. Name must be at least 2 characters.",
    invalidEmail:
      "That email doesn’t look valid. Enter a correct address or clear the field.",
    emailOptionalPlaceholder: "You can add an email anytime",
    settingsTitle: "Settings",
    themeLabel: "Theme",
    themeToggle: "Toggle theme (light / dark)",
    residentsVisibilityLabel: "Show in residents list",
    residentsVisibleOn: "Your name is visible in the building residents list",
    residentsVisibleOff: "Your name is hidden from the residents list",
    notificationsLabel: "Browser notifications",
    notificationsOn: "On",
    notificationsOff: "Off",
    notificationsHint: "",
    logout: "Log out",
    memberSince: "Member since",
    passportTitle: "Unit passport",
    passportHint: "",
    passportNoUnits: "You have not joined any building yet.",
    passportNoEvents: "No records for this unit yet.",
    passportOpen: "Open unit passport",
  },
} as unknown as Messages;

export function ui(locale: AppLocale): Messages {
  return locale === "en" ? EN : AR;
}

export function pickDateLocale(locale: AppLocale): string {
  return locale === "en" ? "en-US" : "ar-SA";
}
